version: 2
registries:

updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    # Automatically update these dependencies
    allow:
      - dependency-name: "org.duckdb:duckdb_jdbc"
