name: Build and Upload Archives Upon Creating Tags

# Run this workflow every time a tag is created
on:
  create:

jobs:
  build:
    # Name the Job
    name: Build tagged commit and upload an archive
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    # Only run for tag creation
    if: github.event.ref_type == 'tag' && github.repository == 'linkedin/venice'
    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # all history for all branches and tags

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '11'

      - name: Upload archive
        env:
          JFROG_USERNAME: ${{ secrets.JFROG_USERNAME }}
          JFROG_API_KEY: ${{ secrets.JFROG_API_KEY }}
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: |
            "-Pversion=${{  github.ref_name }}" publishAllPublicationsToLinkedInJFrogRepository
