name: Build and Upload Archives On Demand

# Run this workflow when triggered manually
on: workflow_dispatch

jobs:
  build:
    # Name the Job
    name: Build tagged commit and upload an archive
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    # timeout-minutes: 120
    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # all history for all branches and tags

      - name: Add upstream remote
        if: github.repository != 'linkedin/venice'
        run: git remote add upstream https://github.com/linkedin/venice

      - name: Fetch upstream refs
        if: github.repository != 'linkedin/venice'
        run: git fetch upstream

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '11'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: clean assemble

      - name: package artifacts
        run: mkdir staging && find . -name "*.jar" -exec cp "{}" staging \;

      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging