name: Build and Upload Archives Upon Pushing Tags

# Run this workflow every time a tag is pushed
on:
  push:
    tags:
      - '*'

jobs:
  build:
    # Name the Job
    name: Build tagged commit and upload an archive
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    if: github.repository == 'linkedin/venice'
    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # all history for all branches and tags

      - name: Set up JDK 11
        uses: actions/setup-java@v5
        with:
          distribution: 'microsoft'
          java-version: '11'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Upload archive
        env:
          JFROG_USERNAME: ${{ secrets.JFROG_USERNAME }}
          JFROG_API_KEY: ${{ secrets.JFROG_API_KEY }}
        run: ./gradlew -Pversion=${{  github.ref_name }} publishAllPublicationsToLinkedInJFrogRepository
