name: Build and Upload Archives On Workflow Call

# Run this workflow on workflow_call
on:
  workflow_call:

jobs:
  build:
    # Name the Job
    name: Build tagged commit and upload an archive
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    # Only run for upstream main
    if: github.repository == 'linkedin/venice'
    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # all history for all branches and tags

      - name: Set up JDK 11
        uses: actions/setup-java@v5
        with:
          distribution: 'microsoft'
          java-version: '11'
      - name: Get Latest Tag
        run: echo "GIT_TAG=`echo $(git describe --tags --abbrev=0 main)`" >> $GITHUB_ENV
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Upload archive
        env:
          JFROG_USERNAME: ${{ secrets.JFROG_USERNAME }}
          JFROG_API_KEY: ${{ secrets.JFROG_API_KEY }}
        run: ./gradlew -Pversion=${{  env.GIT_TAG }} publishAllPublicationsToLinkedInJFrogRepository
